### ISSUE TITLE
variable_set() has been removed

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#11]

**Comment by jamidwyer** [comment]
- [ ] Mandrill Reports
- [ ] Mandrill Activity
- [ ] Mandrill Test

**Comment by jamidwyer** [comment]
Creating the Report and Activity plugins is causing Mailsystem to break because DefaultPluginManager->getDefinition has an empty array. The patch would be to core, but it looks like a tricky one: https://www.drupal.org/node/2031859

Will figure out how to work around this.

**Comment by ruscoe** [comment]
variable_set() now only exists in modules/mandrill_test/mandrill_test.module and that might be removed before the alpha release.
