### ISSUE TITLE
Research Using Mandrill-Integrated Async Processing

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mandrill#2]
- [ ] Investigate custom handling of Drupal queue to combine mail messages into single API request
  - [ ] Merging message arguments
  - [ ] Sending templated messages
- [x] Improve wording on async config option (single API call, recommended, etc)
- [x] Remove queue worker time option
- [x] Remove async limit config option, use hard limit based on 10MB json limit.

**Comment by ruscoe** [comment]
@levelos 

My suggestion:
- Leave the mail queue the way it currently is.
- Remove [mandrill_cron_queue_info](https://github.com/thinkshout/mandrill/blob/7.x-1.x/mandrill.module#L88)
- Add a [cron hook](https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_cron/7)
  - Manually loop through the mail queue and combine all items into a single [API request](https://mandrillapp.com/api/docs/messages.JSON.html#method=send).
  - Clear out the queue.

The only problem I see is the potential reintroduction of problems the queue system is designed to prevent, like the script timing out mid-process. We could always grab a chunk of the queue (max 500 emails, for example,) process that, then wait for the next cron run.

**Comment by levelos** [comment]
That sounds solid, lets give it a go.

**Comment by ruscoe** [comment]
@levelos Committed a working system: https://github.com/thinkshout/mandrill/commit/4a45d648706cbcb46f964337f46fd116ae154e85

We need to discuss merge vars. We have a scheduled meeting today if you're available, otherwise tomorrow would be fine.

**Comment by ruscoe** [comment]
- [x] Update tests to use Drupal mail system, not MandrillMailSystem directly
- [ ] Find solution to unknown message state when received by Mandrill
  - Message body may already be tokenized
  - Message array may not contain expected Mandrill parameters
- [ ] Create mail sending API that conforms with Mandrill API-ready message arrays.

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mandrill Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mandrill/issues/3031679
