### ISSUE TITLE
l() has been removed

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#24]

**Comment by mshaver** [comment]
There were a few additional spots that need to be converted to using the new path system in D8.

**Comment by jamidwyer** [comment]
- [x] main
- [x] reports
- [x] templates
- [ ] activity

**Comment by jamidwyer** [comment]
Updated in the main module and the link still works as expected. Updates in reports and templates didn't break anything. Activity update will require dynamic routes to exist -- those modules will need to work. I'm going to submit a pull request for this and move the activity update to a sub-task of updating the activity submodule.
