### ISSUE TITLE
t() has been removed

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#26]

**Comment by mshaver** [comment]
It actually looks like this function has been removed. What I haven't verified yet is whether it's been replaced with the proper localization functions. I do see @Translation being used in a few places. @jamidwyer why don't you just verify and then we can call this one done.

**Comment by jamidwyer** [comment]
I actually don't see any indication that t() has been removed or deprecated in Drupal 8.
https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/function/t/8

It doesn't appear to break anything where it exists, but I'll spend a few minutes testing whether text is translated as expected.

Possibly the module upgrader has outdated info.

**Comment by jamidwyer** [comment]
I tested translation (enable Language module, hit admin/config/regional/language/add, choose a language you can at least kind of read, hit admin/config/regional/translate, find a Mandrill term and translate it, clear cache and check that your translation shows up) and it works with $this->t() and t().
