### ISSUE TITLE
Create tests for existing code

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#31]
D7 tests are there, but are broken. 
- [ ] Identify what tests are needed.
- [ ] Mandrill Reports tests
- [ ] Mandrill Activity tests
- [ ] Why API key undefined at test time? 
- [ ] Some test may need to be rewritten in phpUnit

**Comment by mshaver** [comment]
D7 tests are there, but are broken. 
- [] Need to rewrite to phpUnit. 
- [] Identify what tests are needed.

**Comment by mshaver** [comment]
Refence #40

**Comment by mshaver** [comment]
Holding off a bit until other issues are complete.

**Comment by ruscoe** [comment]
Tests have been ported. Missing API key is no longer an issue.
