### ISSUE TITLE
Make sure everything on the admin page does something

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#36]

**Comment by ruscoe** [comment]
- [ ] Mandrill API Key
- [ ] From address
- [ ] From name
- [ ] Subaccount
- [ ] Input format
- [ ] Track opens
- [ ] Track clicks
- [ ] Strip query string
- [ ] Content logging blacklist
- [ ] Log sends from module/key pairs
- [ ] Google analytics domains
- [ ] Google analytics campaign
- [ ] Queue outgoing messages
- [ ] Log queued emails
- [ ] Queue worker timeout
