### ISSUE TITLE
Make it wait for cron

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#38]

**Comment by Greg-Boggs** [comment]
Queue outgoing messages.

When set, emails will not be immediately sent. Instead, they will be placed in a queue and sent when cron is triggered.

**Comment by Greg-Boggs** [comment]
My tests work successfully.

**Comment by ruscoe** [comment]
Messages are added to the cron queue, but they are not currently processed. I'll work on that.

For reference, hook_cron_queue_info() has been replaced:

https://www.drupal.org/node/2341649
