### ISSUE TITLE
Make reports landing page

### ISSUE THREAD

**Issue by jamidwyer** [thinkshout/mandrill#42]

**Comment by jamidwyer** [comment]
- [ ] mandrill_get_api_object to getAPIObject
- [ ] create route
- [ ] urls list
- [ ] sending volume graph
- [ ] average open and click rate
- [ ] account summary tab

**Comment by jamidwyer** [comment]
![screen shot 2015-12-11 at 10 37 43 am](https://cloud.githubusercontent.com/assets/509571/11752298/9e315bc8-9ff3-11e5-9570-0318fd1edb11.png)
![screen shot 2015-12-11 at 10 36 55 am](https://cloud.githubusercontent.com/assets/509571/11752303/a27c8806-9ff3-11e5-9660-9ed2259829f7.png)

**Comment by ruscoe** [comment]
Moved to #63
