### ISSUE TITLE
Warning on Install with Drush

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mandrill#54]

**Comment by Greg-Boggs** [comment]
Invalid placeholder (!perms) in string: mandrill defines the following permissions: administer mandrill FormattableMarkup.php:240                                        [error]

**Comment by ruscoe** [comment]
! is no longer a valid placeholder for transactions in D8, but it was still appearing occasionally in old code. I didn't see this with drush 8.1-dev.
