### ISSUE TITLE
Warning message The Mandrill PHP library is not installed. Please see installation directions in README.txt

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mandrill#55]

**Comment by Greg-Boggs** [comment]
Having Trouble installing the library. Or there's a bug in the detection code. Here are my steps so far.

drush dl drupal-8
drush cd drupal-8.0.1
drush dl mailsystem
drush dl mandrill
cd modules/mandrill
composer install
drush en mandrill

**Comment by Greg-Boggs** [comment]
I'm having trouble installing the library. Here are my steps:
drush dl drupal-8
cd drupal-8.0.1
cd modules
git clone git@github.com:thinkshout/mandrill.git
git checkout 8.x-1.x
composer install
drush dl mailsystem
drush en -y mandrill

**Comment by Greg-Boggs** [comment]
composer manager resolves the issue

**Comment by ruscoe** [comment]
This is resolved by using Composer Manager. Instructions have been aded to the README.txt file.
