### ISSUE TITLE
variable_del() has been removed

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mandrill#9]

**Comment by mshaver** [comment]
This is still being called in `mandrill/modules/mandrill_activity/src/MandrillActivityTestCase.php` and `mandrill/modules/mandrill_reports/src/MandrillReportsTestCase.php`.

**Comment by jamidwyer** [comment]
This is removed in this branch, but I need to do further testing on that branch before doing a pull request, because it breaks MailSystem.
